config/routes.rb
Addressbook::Application.routes.draw do
  devise_for :users
  resources :addresses

  resources :contacts do
    member do
      post :change_address
      post :remove_address
    end
    get :find, :on => :collection
  end

  resources :groups do
    get  :create_labels, :on => :member
  end

  get 'settings/address' => 'settings#edit_address', :as => :settings_edit_address
  put 'settings/address' => 'settings#update_address', :as => :settings_update_address
  get 'settings/login_credentials' => 'settings#edit_login_credentials', :as => :settings_edit_login_credentials
  put 'settings/login_credentials' => 'settings#update_login_credentials', :as => :settings_update_login_credentials

  get 'use_desktop_view' => 'main#use_desktop_view'
  get 'use_mobile_view' => 'main#use_mobile_view'

  root :to => 'main#index'
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!, :except => :users

  def index
    @group_list = Group.find_for_list
    @contact_list = Contact.find_for_list
    @address_list = Address.find_for_list
  end

  def users
    @user = User.pluck(:email)
    return @user.to_json
  end
end

app/helpers/main_helper.rb
module MainHelper

  def chunk_list(object_list)
    chunks = {}
    ('A'..'Z').each { |letter| chunks[letter] = [] }

    if object_list.try(:first).class == Contact
      object_list.each { |contact| chunks[contact.last_name[0].chr.upcase] << contact }
    elsif object_list.try(:first).class == Address
      object_list.each do |address|
        first_letter = address.addressee_for_display[0].chr.upcase
        chunks[first_letter] << address unless chunks[first_letter].nil?
      end
    end

    chunks.sort
  end

end

app/views/main/_address_list.html.erb
<%= render :partial => 'main/chunked_list', :locals => {:object_list => object_list} %>

app/views/main/_chunked_list.html.erb
<% chunked_objects = chunk_list(object_list) %>
<% chunked_objects.each do |letter, list| %>
  <% unless list.blank? %>
    <h2 class="letter"><%= letter %></h2>
    <ul>
      <% list.each do |object| %>
        <%= create_link_to(object) %>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/main/_contact_list.html.erb
<%= render :partial => 'main/chunked_list', :locals => {:object_list => object_list} %>

app/views/main/_group_list.html.erb
<ul>
  <% object_list.each do |object| %>
    <%= create_link_to(object) %>
  <% end %>
</ul>

app/views/main/_search_list.html.erb
<ul>
  <% object_list.each do |object| %>
    <%= create_link_to(object) %>
  <% end %>
</ul>

app/views/main/index.html.erb
<div id="main" dojoType="dijit.layout.BorderContainer">
  <div id="menu" dojoType="dijit.layout.AccordionContainer" region="leading">
    <div dojoType="dijit.layout.AccordionPane" title="Search" class="menuContent" selected="true">
      <%= form_tag(find_contacts_path, { :method => :get, :remote => true, :class => 'ajax_request' }) do %>
        <table>
          <tr>
            <td>Last Name:</td>
            <td><%= text_field_tag :last_name, params[:last_name], :size => 10 %></td>
            <td><%= submit_tag 'Search' %></td>
          </tr>
        </table>
      <% end %>
      <div id="contactSearchResults"></div>
      <p><%= link_to 'Switch to mobile view', use_mobile_view_path if is_mobile_device? %></p>
    </div>

    <div dojoType="dijit.layout.AccordionPane" title="Contacts" class="menuContent">
      <div id="contactList">
        <%= render :partial => 'contact_list', :locals => {:object_list => @contact_list} %>
      </div>
      <%= form_tag(new_contact_path, { :method => :get, :remote => true, :class => 'ajax_request' }) do %>
        <%= submit_tag 'Add Contact' %>
      <% end %>
    </div>

    <div dojoType="dijit.layout.AccordionPane" title="Addresses" class="menuContent">
      <div id="addressList">
        <%= render :partial => 'address_list', :locals => {:object_list => @address_list} %>
      </div>
    </div>

    <div dojoType="dijit.layout.AccordionPane" title="Groups" class="menuContent">
      <div id="groupList">
        <%= render :partial => 'group_list', :locals => {:object_list => @group_list} %>
      </div>
      <%= form_tag(new_group_path, { :method => :get, :remote => true, :class => 'ajax_request' }) do %>
        <%= submit_tag 'Add Group' %>
      <% end %>
    </div>

    <div dojoType="dijit.layout.AccordionPane" title="Settings" class="menuContent">
      <ul>
        <div id="settings">
          <li>
            <%= link_to('Home Address', settings_edit_address_path,
                  :method => :get, :remote => true, :class => 'ajax_request', :id => 'edit_home_address') %>
          </li>
          <li>
            <%= link_to('Login Credentials', settings_edit_login_credentials_path,
                  :method => :get, :remote => true, :class => 'ajax_request', :id => 'edit_login_credentials') %>
          </li>
        </div>
      </ul>
    </div>
  </div>

  <div dojoType="dijit.layout.ContentPane" region="center">
    <div id="content">
      <p>Welcome to your Address Book</p>
    </div>
  </div>

</div>

app/views/main/index.mobile.erb
<div data-role="header" data-theme="b">
  <h1>Address Book</h1>
</div>

<div data-role="content">
  <% chunked_contacts = chunk_list(@contact_list) %>
  <% chunked_contacts.each do |letter, contact_list| %>
    <% unless contact_list.blank? %>
      <div data-role="collapsible" data-collapsed="true" data-theme="c">
        <h3><%= letter %></h3>
        <ul data-role="listview" data-inset="true" data-theme="d">
          <% contact_list.each do |contact| %>
            <li><%= link_to contact.full_name_last_first, contact_path(contact) %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
</div>

<div data-role="footer" data-theme="b">
  <p id="switch_to_desktop"><%= link_to 'Switch to desktop view', use_desktop_view_path, {:rel => 'external'} %></p>
</div>