config/routes.rb
Addressbook::Application.routes.draw do
  devise_for :users
  resources :addresses

  resources :contacts do
    member do
      post :change_address
      post :remove_address
    end
    get :find, :on => :collection
  end

  resources :groups do
    get  :create_labels, :on => :member
  end

  get 'settings/address' => 'settings#edit_address', :as => :settings_edit_address
  put 'settings/address' => 'settings#update_address', :as => :settings_update_address
  get 'settings/login_credentials' => 'settings#edit_login_credentials', :as => :settings_edit_login_credentials
  put 'settings/login_credentials' => 'settings#update_login_credentials', :as => :settings_update_login_credentials

  get 'use_desktop_view' => 'main#use_desktop_view'
  get 'use_mobile_view' => 'main#use_mobile_view'

  root :to => 'main#index'
end

app/models/group.rb
require 'prawn/labels'

class Group < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :addresses

  before_destroy :clear_address_associations

  validates_presence_of :name

  def self.find_for_list
    Group.order('name')
  end

  def addresses_not_included
    included_ids = self.address_ids
    if included_ids.blank?
      Address.eligible_for_group
    else
      Address.eligible_for_group.where(['id not in (?)', included_ids])
    end
  end

  def create_labels(label_type)
    Prawn::Labels.render(self.addresses, :type => label_type) do |pdf, a|
      pdf.text a.addressee
      pdf.text a.address1
      pdf.text a.address2 unless a.address2.blank?
      pdf.text a.city + ', ' + a.state + ' ' + a.zip
    end
  end

  private

  def clear_address_associations
    addresses.clear
  end

end

app/controllers/group_controller.rb
class GroupController < ApplicationController

  def new
    @group = Group.new
    include_common_data
    render 'edit_group'
  end

  def create
    @group = Group.new(params[:group])
    @saved = @group.save
    @group_list = Group.find_for_list
    include_common_data
    render 'edit_group'
  end

  def show
    @group = Group.find_by_id(params[:id])
    include_common_data
    render 'edit_group'
  end

  def edit
    @group = Group.find_by_id(params[:id])
    include_common_data
    render 'edit_group'
  end

  def update
    @group = Group.find_by_id(params[:id])
    @group.attributes = params[:group]
    @group.addresses = (params[:included].blank? ? [] : Address.find(params[:included]))
    @saved = @group.save
    include_common_data
    render 'edit_group'
  end
  
  def destroy
    @group = Group.find_by_id(params[:id])
    @group.ergo.destroy
    include_common_data
    render 'delete_group'
  end

  def create_labels
    @group = Group.find_by_id(params[:id])
    file_path = @group.create_labels(params[:label_type])
    send_data(File.read(file_path), :filename => "labels.pdf", :type => "application/pdf")
    include_common_data
  end
  
  private

    def include_common_data
      @included = @group.addresses.includes([:contacts, :address_type])
      @not_included = @group.addresses_not_included
      @label_types = Pdf::Label::Batch.all_template_names.sort!
    end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_filter :load_group, :except => [:new, :create]

  def new
    @group = Group.new
    include_common_data
    render 'edit_group'
  end

  def create
    @group = Group.new(group_params[:group])
    @saved = @group.save
    @group_list = Group.find_for_list
    include_common_data
    render 'edit_group'
  end

  def show
    include_common_data
    render 'edit_group'
  end

  def update
    @group.attributes = group_params[:group] || {}
    @group.addresses = (params[:included].blank? ? [] : Address.find(params[:included]))
    @saved = @group.save
    include_common_data
    render 'edit_group'
  end

  def destroy
    @group.try(:destroy)
    include_common_data
    render 'delete_group'
  end

  def create_labels
    labels = @group.create_labels(params[:label_type])
    send_data(labels, :filename => 'labels.pdf', :type => 'application/pdf')
    include_common_data
  end

  private

  def load_group
    @group = Group.find_by_id(params[:id])
  end

  def include_common_data
    @included = @group.addresses.includes([:contacts, :address_type])
    @not_included = @group.addresses_not_included
    @label_types = Prawn::Labels.types.keys.sort!
  end

  def group_params
    params.permit(:group => [:name], :included => [])
  end

end

app/helpers/group_helper.rb
require 'inline'
module GroupHelper

  def get_label_options(label_types)
    label_options = "" 
    label_types.each { |label_type| label_options << "<option value='#{label_type.gsub(' ', '_')}'>#{label_type}</option>" }
    label_options.html_safe
  end

  def options_for_group_members(group_members)
    html = ""
    group_members.each do |address|
      html << "<option value='#{address.id}' title='#{address.mailing_address}'>#{address.addressee_for_display}</option>"
    end
    html.html_safe
  end

  def sbook
    inline(:C) do |builder|
      # put your C++ code here
    end
  end

end

app/views/groups/_deleted_group.html.erb
Group <%= @group.name %> was deleted successfully.

app/views/groups/_group.html.erb
<%= error_messages_for :group %>
<%= form_tag(@group, { :method => put_or_post(@group), :remote => true, :class => 'ajax_request' }) do %>

  <h3>Group Info</h3>
  <div class="section">
    <table>
      <tr>
        <td><label>Name:</label></td>
        <td><%= text_field :group, :name, :size => 20 %></td>
      </tr>
    </table>
  </div>

  <% unless @group.id.nil? %>
    <h3>Group Members</h3>
    <div class="section">
      <div id="displayGroupMembers">
        <ul>
          <div id="groupMembers">
            <%=
              @included.to_a.sort! { |x,y| x.compare_by_primary_contact(y) }
              render :partial => 'group_list', :collection => @included
            %>
          </div>
        </ul>

        <%= link_to('Maintain Group Members', '#', :class => 'maintain_group_members_link') %>
      </div>

      <div id="editGroupMembers" style="display:none;">
        <%= render :partial => 'maintain_group_members' %>
      </div>
    </div>

    <h3>Labels</h3>
    <div class="section">
      <label>Label Type:</label>
      <%= select_tag :label_type, get_label_options(@label_types),
            { :id => 'labelTypeSelector',
              :onchange => "updateCreateLabelsLink('#{url_for(:action => :create_labels, :id => @group)}');" } %>

      <span id="createLabelsLink">
        <%= link_to 'Create Labels', create_labels_group_path(@group, :label_type => @label_types.first) %>
      </span>
    </div>
  <% end %>

  <br />
  <div class="buttons">
    <%= submit_tag 'Save', :class => 'positive', :onclick => 'selectAllIncludedGroupMembers();' %>
  </div>
<% end %>

<%= create_cancel_delete_links(@group) %>

app/views/groups/_group_list.html.erb
<li id="<%= group_list.id %>"><%= group_list.addressee_for_display %></li>

app/views/groups/_maintain_group_members.html.erb
<div align="center">
  <table id="maintainGroupTable">
    <tr>
      <th>Not Included</th>
      <th>&nbsp;</th>
      <th>Included</th>
    </tr>

    <tr>
      <td id="notIncludedListCell" class="groupListAddresses">
        <ul>
          <div id="notIncludedList">
            <%=
              @not_included.to_a.sort! { |x,y| x.compare_by_primary_contact(y) }
              select_tag(:not_included,
                options_for_group_members(@not_included),
                :multiple => true, :class => 'selectGroupAddresses', :onDblclick => 'includeSelectedMembers();')
            %>
          </div>
        </ul>
      </td>

      <td id="maintainGroupControls">
        <%= link_to('<<', '#', :class => 'exclude_all_members_link') %>
        <%= link_to('<', '#', :class => 'exclude_selected_members_link') %>
        <br/>
        <%= link_to('>', '#', :class => 'include_selected_members_link') %>
        <%= link_to('>>', '#', :class => 'include_all_members_link') %>
      </td>

      <td id="includedListCell" class="groupListAddresses">
        <ul>
          <div id="includedList">
            <%=
              @included.to_a.sort! { |x,y| x.compare_by_primary_contact(y) }
              select_tag(:included,
                options_for_group_members(@included),
                :multiple => true, :class => 'selectGroupAddresses', :onDblclick => 'excludeSelectedMembers();')
            %>
          </div>
        </ul>
      </td>
    </tr>
  </table>
</div>

app/views/groups/delete_group.js.erb
$('#content').html("<%= j render(:partial => 'deleted_group') %>");
<%= remove_from_list(@group) %>

app/views/groups/edit_group.js.erb
$('#content').html("<%= j render(:partial => 'group') %>");
<%= update_list(@group, @group_list) %>
<%= highlight_in_list(@group) if @saved %>