config/routes.rb
Addressbook::Application.routes.draw do
  devise_for :users
  resources :addresses

  resources :contacts do
    member do
      post :change_address
      post :remove_address
    end
    get :find, :on => :collection
  end

  resources :groups do
    get  :create_labels, :on => :member
  end

  get 'settings/address' => 'settings#edit_address', :as => :settings_edit_address
  put 'settings/address' => 'settings#update_address', :as => :settings_update_address
  get 'settings/login_credentials' => 'settings#edit_login_credentials', :as => :settings_edit_login_credentials
  put 'settings/login_credentials' => 'settings#update_login_credentials', :as => :settings_update_login_credentials

  get 'use_desktop_view' => 'main#use_desktop_view'
  get 'use_mobile_view' => 'main#use_mobile_view'

  root :to => 'main#index'
end

app/models/settings.rb
class Settings < ActiveRecord::Base

  def self.update_login_credentials(username, password, password_confirmation, current_password)
    actual_current_password = Settings.password
    if !actual_current_password.blank? && Password.create_hash(current_password) != actual_current_password
      'The current password specified is not valid'
    elsif (username.blank? || password.blank? || password_confirmation.blank?) && !(username.blank? && password.blank? && password_confirmation.blank?)
      'You must specify a username, password, and password confirmation'
    elsif password != password_confirmation
      'The password and password confirmation do not match'
    else
      Settings.username = username
      Settings.password = password
      nil
    end
  end

  def self.save_home_address(address)
    if address.valid?
      Settings.update(:address, address.address1)
      Settings.update(:city, address.city)
      Settings.update(:state, address.state)
      Settings.update(:zip, address.zip)
      true
    else
      false
    end
  end

  def self.home_address
    Address.new(:address1 => address, :city => city, :state => state, :zip => zip)
  end

  def self.username
    self.get(:username)
  end

  def self.username=(data)
    Settings.update(:username, data)
  end

  def self.password
    self.get(:password)
  end

  def self.password=(data)
    data = Password.create_hash(data) unless data.blank?
    Settings.update(:password, data)
  end

  def self.address
    self.get(:address)
  end

  def self.city
    self.get(:city)
  end

  def self.state
    self.get(:state)
  end

  def self.zip
    self.get(:zip)
  end

  private

  def self.get(key)
    Settings.find_by_key(key).try(:value)
  end

  def self.update(key, value)
    settings = Settings.find_by_key(key) || Settings.create(:key => key)
    settings.update_attribute(:value, value)
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  def edit_address
    @address = Settings.home_address
    render 'address'
  end

  def update_address
    @address = Address.new(settings_params[:address])
    @saved = true if Settings.save_home_address(@address)
    render 'address'
  end

  def edit_login_credentials
    @username = Settings.username
    @password = Settings.password
    @demo = (ENV['DEMO'] == 'true')
    render 'login_credentials'
  end

  def update_login_credentials
    @demo = (ENV['DEMO'] == 'true')
    unless @demo
      @username = settings_params[:username]
      @password = settings_params[:password]
      @password_confirmation = settings_params[:password_confirmation]
      @current_password = settings_params[:current_password]

      message = Settings.update_login_credentials(@username, @password, @password_confirmation, @current_password)
      message.nil? ? @saved = true : flash.now[:notice] = message
    end
    render 'login_credentials'
  end

  private

  def settings_params
    params.permit({:address => [:address1, :address2, :city, :state, :zip]}, :username, :password, :password_confirmation, :current_password)
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_address.html.erb
<%= error_messages_for :address %>

<%= form_tag(settings_update_address_path, { :method => :put, :remote => true, :class => 'ajax_request' }) do %>
  <h3>Home Address</h3>
  <p>
    If a home address is specified, it is used to calculate directions from the home
    address to the address of your contacts.
  </p>
  <div class="section">
    <%= render :partial => 'shared/address_fields', :locals => { :address => @address, :disable_address2 => true } %>
  </div>

  <br />
  <div class="buttons">
    <%= submit_tag "Save", :class => "positive" %>
  </div>
<% end %>

<div class="buttons">
  <%= button_to("Cancel", settings_edit_address_path, :method => :get, :remote => true, :class => 'ajax_request regular') %>
</div>

app/views/settings/_login_credentials.html.erb
<% if flash.now[:notice] %>
  <div class="errorExplanation" id="errorExplanation"><h2>1 error prohibited these credentials from being saved</h2><p><%= flash.now[:notice] %></p></div>
<% end %>

<h3>Login Credentials</h3>
<p>
  If a username and password are specified, then they will be used to authenticate the user using HTTP Basic
  Authentication when the addressbook is accessed.
</p>

<% if @demo %>
  <p><strong>This feature is not available in the demo.</strong></p>
<% else %>
  <%= form_tag(settings_update_login_credentials_path, { :method => :put, :remote => true, :class => 'ajax_request' }) do %>
    <div class="section">
      <table>
        <tr>
          <td><label>Username:</label></td>
          <td><%= text_field_tag 'username', @username, :size => 20 %></td>
        </tr>
        <% if @password %>
          <tr>
            <td><label>Current password:</label></td>
            <td><%= password_field_tag 'current_password', @current_password, :size => 20 %></td>
          </tr>
        <% end %>
        <tr>
          <td><label>New password:</label></td>
          <td><%= password_field_tag 'password', @password, :size => 20 %></td>
        </tr>
        <tr>
          <td><label>Password confirmation:</label></td>
          <td><%= password_field_tag 'password_confirmation', @password_confirmation, :size => 20 %></td>
        </tr>
      </table>
    </div>

    <br />
    <div class="buttons">
      <%= submit_tag "Save", :class => "positive" %>
    </div>
  <% end %>

  <div class="buttons">
    <%= button_to("Cancel", settings_edit_login_credentials_path, :method => :get, :remote => true, :class => 'ajax_request regular') %>
  </div>
<% end %>

app/views/settings/address.js.erb
$('#content').html("<%= j render(:partial => 'address') %>");
<% if @saved %>
  $('#edit_home_address').effect('highlight', {}, 2000);
<% end %>

app/views/settings/login_credentials.js.erb
$('#content').html("<%= j render(:partial => 'login_credentials') %>");
<% if @saved %>
  $('#edit_login_credentials').effect('highlight', {}, 2000);
<% end %>