config/routes.rb
Addressbook::Application.routes.draw do
  devise_for :users
  resources :addresses

  resources :contacts do
    member do
      post :change_address
      post :remove_address
    end
    get :find, :on => :collection
  end

  resources :groups do
    get  :create_labels, :on => :member
  end

  get 'settings/address' => 'settings#edit_address', :as => :settings_edit_address
  put 'settings/address' => 'settings#update_address', :as => :settings_update_address
  get 'settings/login_credentials' => 'settings#edit_login_credentials', :as => :settings_edit_login_credentials
  put 'settings/login_credentials' => 'settings#update_login_credentials', :as => :settings_update_login_credentials

  get 'use_desktop_view' => 'main#use_desktop_view'
  get 'use_mobile_view' => 'main#use_mobile_view'

  root :to => 'main#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :address

  before_save :sanitize_phone_numbers
  after_save :link_contact_to_address
  before_destroy :remove_contact_from_address

  validates_presence_of :first_name, :last_name, :prefix
  validate :validate_phone_numbers

  scope :with_address, -> { where('address_id is not null') }

  def self.find_for_list
    Contact.order('last_name, first_name')
  end

  def full_name_last_first
    "#{last_name}, #{first_name}"
  end

  def has_address?
    !address.blank? && !address.is_address_empty?
  end

  def assign_address(new_address)
    self.address.unlink_contact(self) if self.address
    self.address = new_address
  end

  def remove_address
    old_address_id = self.address_id
    self.address = nil

    if save
      Address.find_by_id(old_address_id).unlink_contact(self)
      old_address_id
    else
      nil
    end
  end

  private

  def link_contact_to_address
    address.try(:link_contact) unless self.destroyed?
  end

  def sanitize_phone_numbers
    self.cell_phone = Phone.sanitize(self.cell_phone)
    self.work_phone = Phone.sanitize(self.work_phone)
  end

  def remove_contact_from_address
    self.address = nil
    save
    Address.remove_contact(self)
  end

  def validate_phone_numbers
    if !self.cell_phone.blank? && !Phone.valid?(self.cell_phone)
      errors.add(:cell_phone, 'is not valid')
    end

    if !self.work_phone.blank? && !Phone.valid?(self.work_phone)
      errors.add(:work_phone, 'is not valid')
    end
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @contact = Contact.new
    render 'edit_contact'
  end

  def create
    @contact = Contact.new(params[:contact])

    new_address = parse_address
    if new_address && new_address.valid?
      assigning_new_address_object = params[:address_specification_type] == 'existing_address'
      assign_address_to_contact(new_address, assigning_new_address_object)
      @address_list = Address.find_for_list
    end

    @saved = @contact.save
    @contact_list = Contact.find_for_list
    render 'edit_contact'
  end

  def show
    @contact = Contact.find_by_id(params[:id])
    if is_mobile_device?
      render 'show_contact'
    else
      render 'edit_contact'
    end
  end

  def edit
    @contact = Contact.find_by_id(params[:id])
    render 'edit_contact'
  end

  def update
    @contact = Contact.find_by_id(params[:id])
    @contact.attributes = params[:contact]

    render_target = 'edit_contact'
    new_address = parse_address
    if new_address && new_address.valid? && new_address.different_from?(@contact.address)
      if changing_address_for_multiple_contacts?
        session[:changed_address] = new_address
        render_target = 'edit_contact_with_shared_address'
      else
        assigning_new_address_object = params[:address_specification_type] == 'existing_address'
        new_address_saved = assign_address_to_contact(new_address, assigning_new_address_object)
      end
    end

    @saved = @contact.errors.blank? && @contact.save
    @address_list = Address.find_for_list if new_address_saved

    if new_address && new_address.different_from?(@contact.address)
      @address = new_address
    else
      @address = @contact.address || Address.new
    end

    render :template => "contact/#{render_target}"
  end

  def destroy
    @contact = Contact.find_by_id(params[:id])
    @old_address = Address.new
    @old_address.attributes = @contact.address.ergo.attributes
    @contact.ergo.destroy
    @address_list = Address.find_for_list if @contact.address.nil?
    render 'delete_contact'
  end

  def change_address_for_contact
    @contact = Contact.find_by_id(params[:id])
    assigning_new_address_object = params[:submit_id] == 'no'
    new_address = assign_address_to_contact(session[:changed_address], assigning_new_address_object)
    @contact.save

    @address = @contact.address || Address.new
    @address_list = Address.find_for_list if new_address
    render :template => 'contact/edit_contact'
  end
  
  def remove_address_from_contact
    @contact = Contact.find_by_id(params[:id])
    @old_address = @contact.address
    @old_address_id = @contact.remove_address
    @saved = true unless @old_address_id.nil?
    @address_list = Address.find_for_list
    render :template => 'contact/edit_contact'
  end

  def find
    @contact_list = Contact.where(["upper(last_name) like ?", params[:last_name].upcase << "%"]).
                            order('last_name, first_name')
    render 'find_contact'
  end
  
  private

    def changing_address_for_multiple_contacts?
      @contact.address && @contact.address.contacts.size > 1
    end

    def assign_address_to_contact(new_address, assigning_new_address_object)
      if @contact.address.nil? || assigning_new_address_object
        @contact.assign_address(new_address)
        true
      else
        @contact.address.attributes = new_address.attributes
        false
      end
    end

    def parse_address
      if params[:address_specification_type] == 'existing_address'
        other = Contact.find_by_id(params[:other_id])
        other.address
      elsif specified_address?
        address = Address.new(params[:address])
        @contact.errors.add(:base, 'Please specify a valid address') unless address.valid?
        address
      end
    end

    def specified_address?
      params[:address_specification_type] == 'specified_address' ||
              (params[:address] && params[:address][:home_phone] && !params[:address][:home_phone].blank?)
    end
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_filter :load_contact, :except => [:new, :create, :find]

  def new
    @contact = Contact.new
    render 'edit_contact'
  end

  def create
    @contact = Contact.new(contact_params)

    new_address = parse_address
    if new_address && new_address.valid?
      assigning_new_address_object = (params[:address_specification_type] == 'existing_address')
      assign_address_to_contact(new_address, assigning_new_address_object)
      @address_list = Address.find_for_list
    end

    @saved = @contact.save
    @contact_list = Contact.find_for_list
    render 'edit_contact'
  end

  def show
    @address = @contact.address || Address.new
    is_mobile_device? ? render('show_contact') : render('edit_contact')
  end

  def update
    @contact.attributes = contact_params

    render_target = 'edit_contact'
    new_address = parse_address
    if new_address && new_address.valid? && new_address.different_from?(@contact.address)
      if changing_address_for_multiple_contacts?
        session[:changed_address] = new_address.to_json
        render_target = 'edit_contact_with_shared_address'
      else
        assigning_new_address_object = (params[:address_specification_type] == 'existing_address')
        new_address_saved = assign_address_to_contact(new_address, assigning_new_address_object)
      end
    end

    @saved = @contact.errors.blank? && @contact.save
    @address_list = Address.find_for_list if new_address_saved

    if new_address && new_address.different_from?(@contact.address)
      @address = new_address
    else
      @address = @contact.address || Address.new
    end

    render render_target
  end

  def destroy
    @old_address = Address.new
    @old_address.attributes = @contact.address.try(:attributes) || {}
    @contact.try(:destroy)
    @address_list = Address.find_for_list if @contact.address.nil?
    render 'delete_contact'
  end

  def change_address
    assigning_new_address_object = params[:submit_id] == 'no'
    changed_address_params = JSON.parse(session[:changed_address])
    changed_address = Address.find_by_id(changed_address_params['id']) || Address.new
    changed_address.attributes = changed_address_params
    new_address = assign_address_to_contact(changed_address, assigning_new_address_object)
    @contact.save

    @address = @contact.address || Address.new
    @address_list = Address.find_for_list if new_address
    render 'edit_contact'
  end

  def remove_address
    @old_address = @contact.address
    @old_address_id = @contact.remove_address
    @saved = true unless @old_address_id.nil?
    @address_list = Address.find_for_list
    render 'edit_contact'
  end

  def find
    @contact_list = Contact.where(["upper(last_name) like ?", params[:last_name].upcase << "%"]).
                            order('last_name, first_name')
    render 'find_contact'
  end

  private

  def load_contact
    @contact = Contact.find_by_id(params[:id])
  end

  def changing_address_for_multiple_contacts?
    @contact.address && @contact.address.contacts.size > 1
  end

  def assign_address_to_contact(new_address, assigning_new_address_object)
    if @contact.address.nil? || assigning_new_address_object
      @contact.assign_address(new_address)
      true
    else
      @contact.address.attributes = new_address.attributes.reject { |k,v| k == 'id' }
      false
    end
  end

  def parse_address
    if params[:address_specification_type] == 'existing_address'
      other = Contact.find_by_id(params[:other_id])
      other.address
    elsif specified_address?
      address = Address.new(address_params)
      @contact.errors.add(:base, 'Please specify a valid address') unless address.valid?
      address
    end
  end

  def specified_address?
    params[:address_specification_type] == 'specified_address' ||
            (params[:address] && params[:address][:home_phone] && !params[:address][:home_phone].blank?)
  end

  def contact_params
    params.require(:contact).permit(:prefix, :first_name, :middle_name, :last_name, :birthday, :work_phone, :cell_phone, :email, :website, :address_id)
  end

  def address_params
    params.require(:address).permit(:address1, :address2, :city, :state, :zip, :home_phone, :contact1_id, :contact2_id, :address_type_id)
  end

end

app/helpers/contact_helper.rb
module ContactHelper

  def add_map_and_directions_links(contact)
    map_query = contact.address.address1 + ',' +
                contact.address.city + ',' +
                contact.address.state + ' ' +
                contact.address.zip
    map_query.gsub!(' ', '+')
    map_link = 'http://maps.google.com/maps?q=' + map_query
    html = "<a href=\"#{map_link}\" target=\"new\">Map</a>"

    user_address = Settings.home_address
    if !user_address.is_street_address_empty? && !mobile_device?
      directions_query = 'daddr=' +
        contact.address.address1 + ',' +
        contact.address.city + ',' +
        contact.address.state + ' ' +
        contact.address.zip
      directions_query += '&saddr=' +
        user_address.address1 + ',' +
        user_address.city + ',' +
        user_address.state + ' ' +
        user_address.zip
      directions_query.gsub!(' ', '+')
      directions_link = 'http://maps.google.com/maps?' + directions_query
      html += " | <a href=\"#{directions_link}\" target=\"new\">Directions</a>"
    end

    html.html_safe
  end

  def display_style_for_address(address)
    (address.blank? || address.is_address_empty?) ? "display:none;" : ""
  end

  def display_style_for_specify_address(address)
    (address.blank? || address.is_address_empty?) ? "" : "display:none;"
  end

  def has_contact_info_to_display?(contact)
    !contact.address.try(:home_phone).blank? ||
            !contact.work_phone.blank? ||
            !contact.cell_phone.blank? ||
            !contact.email.blank? ||
            !contact.website.blank?
  end

  private

  def mobile_device?
    respond_to?(:is_mobile_device?) && is_mobile_device?
  end

end

app/views/contacts/_contact.html.erb
<%= error_messages_for :contact %>
<% address = @contact.try(:address) %>
<%= form_tag(@contact, { :method => put_or_post(@contact), :remote => true, :class => 'ajax_request' }) do %>

  <h3>Personal Info</h3>
  <div class="section">
    <table>
      <tr>
        <td><label>Prefix:</label></td>
        <td><%= text_field :contact, :prefix, :size => 5, :id => 'top' %></td>
      </tr>
        <tr>
        <td><label>First Name:</label></td>
        <td><%= text_field :contact, :first_name, :size => 20 %></td>
      </tr>
      <tr>
        <td><label>Middle Name:</label></td>
        <td><%= text_field :contact, :middle_name, :size => 20 %></td>
      </tr>
      <tr>
        <td><label>Last Name:</label></td>
        <td><%= text_field :contact, :last_name, :size => 20 %></td>
      </tr>
      <tr>
        <td><label>Birthdate:</label></td>
        <td><%= text_field :contact, :birthday, :size => 15 %></td>
      </tr>
    </table>
  </div>

  <h3>Contact Info</h3>
  <div class="section">
    <table>
      <tr>
        <td><label>Home Phone:</label></td>
        <td><%= text_field_tag 'address[home_phone]', Phone.format(address.try(:home_phone)), :size => 20 %></td>
        </td>
      </tr>
      <tr>
        <td><label>Work Phone:</label></td>
        <td><%= text_field_tag 'contact[work_phone]', Phone.format(@contact.work_phone), :size => 20 %></td>
      </tr>
      <tr>
        <td><label>Cell Phone:</label></td>
        <td><%= text_field_tag 'contact[cell_phone]', Phone.format(@contact.cell_phone), :size => 20 %></td>
      </tr>
      <tr>
        <td><label>Email Address:</label></td>
        <td><%= text_field :contact, :email, :size => 30 %></td>
      </tr>
      <tr>
        <td><label>Web Page:</label></td>
        <td><%= text_field :contact, :website, :size => 45 %></td>
      </tr>
    </table>
  </div>

  <h3>Address</h3>
  <div class="section">
    <% if @contact.has_address? %>
      <p id="address" style="<%= display_style_for_address(address) %>">
        <%= address.address1 %><br />
        <% unless address.address2.blank? %>
          <%= address.address2 %><br />
        <% end %>
        <%= address.city + ', ' + address.state + ' ' + address.zip %>
      </p>
    <% end %>

    <div id="specifyAddress" style="<%= display_style_for_specify_address(address) %>">
      <% if Address.all.size > 0 %>
        <p>
          <%= radio_button_tag(:address_specification_type, :existing_address, false, :id => 'existing_address') %>
          <%= label_tag :existing_address, 'Associate contact with an existing address' %>
        </p>
        <p class="addressOption">
          <%= select_tag :other_id, options_from_collection_for_select(
                Contact.with_address.order('last_name, first_name'), 'id', 'full_name_last_first') %>
        </p>
      <% end %>

      <p>
        <%= radio_button_tag(:address_specification_type, :specified_address,
              (!address.try(:is_empty?) || (!address.try(:is_empty?) && !address.try(:valid?))), :id => 'specified_address') %>
        <%= label_tag :specified_address, 'Associate contact the specified address' %>
        <div class="addressOption">
          <%= render :partial => 'shared/address_fields' %>
        </div>
      </p>
    </div>

    <% if @contact.has_address? %>
      <p>
        <%= link_to('Edit Address', '#', :class => 'edit_address_link') %> |
        <%= link_to('Address Details', address, :method => :get, :remote => true, :class => 'ajax_request') %> |
        <%= link_to('Delete Address', remove_address_contact_path(@contact),
                    :method => :post, :remote => true, :class => 'ajax_request', :data => { :confirm => "Are you sure you would like to delete the address for #{@contact.first_name} #{@contact.last_name}?" }) %> |
        <%= add_map_and_directions_links(@contact) %> <br />
      </p>
    <% end %>
  </div>

  <br />
  <div class="buttons">
    <%= submit_tag "Save", :class => "positive" %>
  </div>
<% end %>

<%= create_cancel_delete_links(@contact) %>

<%= render :partial => 'multiple_address_confirmation_form' unless address.nil? %>

<script>
$(document).ready(function() {
  $('#other_id').click(function() { selectExistingAddressOption(); });

  $('#address_home_phone').keydown(function() { selectSpecifiedAddressOption(); });
  $('#address_address1').keydown(function() { selectSpecifiedAddressOption(); });
  $('#address_address2').keydown(function() { selectSpecifiedAddressOption(); });
  $('#address_city').keydown(function() { selectSpecifiedAddressOption(); });
  $('#address_state').keydown(function() { selectSpecifiedAddressOption(); });
  $('#address_zip').keydown(function() { selectSpecifiedAddressOption(); });
});
</script>

app/views/contacts/_deleted_contact.html.erb
<%= @contact.first_name %> <%= @contact.last_name %> was deleted successfully.

app/views/contacts/_multiple_address_confirmation_form.html.erb
<a id="multipleAddressConfirmationLink" href="#multipleAddressConfirmation" style="display:none"></a>
<div style="display:none">
  <div id="multipleAddressConfirmation">
    <%= form_tag(change_address_contact_path(@contact), { :remote => true, :id => 'multipleAddressConfirmationForm', :class => 'ajax_request' }) do %>
      <p>
        The following contacts live at this address and have this phone number:
        <p>
          <% @contact.address.contacts.each do |contact| %>
            <strong><%= contact.full_name_last_first %></strong><br/>
          <% end %>
        </p>
      </p>

      <p>Would you like to change the address and phone number for all of them?</p>

      <p>
        <%= hidden_field_tag 'submit_id' %>
        <%= submit_tag 'Yes, change for all', :onclick => 'changeAddressForAll();' %>
        <%= submit_tag "No, just change #{@contact.first_name}", :onclick => 'changeAddressForSpecified();' %>
        <br/>
      </p>

      <p><%= link_to('Cancel', '#', :class => 'cancel_multiple_address_confirmation_link') %></p>
    <% end %>
  </div>
</div>

<script>
  jQuery(document).ready(function() {
    jQuery("a#multipleAddressConfirmationLink").fancybox({
      'width' : 400,
      'height' : 250,
      'autoDimensions' : false,
      'hideOnOverlayClick' : false,
      'enableEscapeButton' : true,
      'showCloseButton' : false
    });
  });
</script>

app/views/contacts/delete_contact.js.erb
$('#content').html("<%= j render(:partial => 'deleted_contact') %>");
<%= remove_from_list(@contact) %>
<% address = @old_address || @contact.address %>

<% if !@address_list.nil? %>
  <%= update_list(address, @address_list, true) %>
<% elsif !address.nil? %>
  <%= update_list(address, nil) %>
<% end %>

app/views/contacts/edit_contact.js.erb
$('#content').html("<%= j render(:partial => 'contact') %>");
<%= update_list(@contact, @contact_list) %>

<% address = @old_address || @contact.address %>
<%= update_list(address, @address_list) unless address.nil? %>

$('#top').focus();
<%= highlight_in_list(@contact) if @saved %>

app/views/contacts/edit_contact_with_shared_address.js.erb
$('#multipleAddressConfirmationLink').click();

app/views/contacts/find_contact.js.erb
<% if @contact_list.blank? %>
  $('#contactSearchResults').html('<p><em>No results found</em></p>');
<% else %>
  $('#contactSearchResults').html("<%= j render(:partial => 'main/search_list', :locals => {:object_list => @contact_list}) %>");
<% end %>

app/views/contacts/show_contact.mobile.erb
<div data-role="header" data-theme="b">
  <h1><%= @contact.last_name %></h1>
</div>

<div data-role="content">

<h2><%= @contact.prefix %> <%= @contact.first_name %> <%= @contact.last_name %></h2>

<% if has_contact_info_to_display?(@contact) %>
  <h3>Contact Info</h3>
  <div class="section">
    <table>
      <% if !@contact.address.try(:home_phone).blank? %>
        <tr>
          <td><label>Home:</label></td>
          <td><%= phone_to(@contact.address.home_phone) %></td>
          </td>
        </tr>
      <% end %>

      <% unless @contact.work_phone.blank? %>
        <tr>
          <td><label>Work:</label></td>
          <td><%= phone_to(@contact.work_phone) %></td>
        </tr>
      <% end %>

      <% unless @contact.cell_phone.blank? %>
        <tr>
          <td><label>Cell:</label></td>
          <td><%= phone_to(@contact.cell_phone) %></td>
        </tr>
      <% end %>

      <% unless @contact.email.blank? %>
        <tr>
          <td><label>Email:</label></td>
          <td><%= mail_to @contact.email %></td>
        </tr>
      <% end %>

      <% unless @contact.website.blank? %>
        <tr>
          <td><label>Web:</label></td>
          <td><%= auto_link @contact.website, :html => {:rel => 'external'} %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

<% if @contact.has_address? %>
  <h3>Address</h3>
  <div class="section">
    <p id="address">
      <%= @contact.address.address1 %><br />
      <% unless @contact.address.address2.blank? %>
        <%= @contact.address.address2 %><br />
      <% end %>
      <%= @contact.address.city + ', ' + @contact.address.state + ' ' + @contact.address.zip %>
    </p>
    <p id="mapLinks"><%= add_map_and_directions_links(@contact) %></p>
  </div>
<% end %>

</div>